//! PUT /api/gym/exercises/{id}/image and GET /api/gym/images/{key}

use libtest_mimic::Trial;
use reqwest::StatusCode;
use serde_json::json;

use crate::client::{Client, Ctx, TOKEN};
use crate::fixtures::{exercise, now_ms, uuid};

const PNG: &[u8] = b"\x89PNG\r\n\x1a\n fake png body";

/// Adds this file's trials to the run.
pub fn register(trials: &mut Vec<Trial>, ctx: &Ctx) {
    trials.push(ctx.trial("gym::images::upload_then_read", upload_then_read));
    trials.push(ctx.trial(
        "gym::images::unknown_exercise_is_404",
        unknown_exercise_is_404,
    ));
    trials.push(ctx.trial("gym::images::wrong_type_is_415", wrong_type_is_415));
    trials.push(ctx.trial("gym::images::too_large_is_413", too_large_is_413));
    trials.push(ctx.trial(
        "gym::images::missing_or_bad_key_is_404",
        missing_or_bad_key_is_404,
    ));
    trials.push(ctx.trial("gym::images::requires_token", requires_token));
}

async fn seeded_exercise(c: &Client) -> String {
    let id = uuid();
    let (status, body) = c
        .sync(0, json!({ "exercise": [exercise(&id, "Photo", now_ms())] }))
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");
    id
}

// The key is generated by the API, always lowercase; a case fold would hide a bug.
#[allow(clippy::case_sensitive_file_extension_comparisons)]
async fn upload_then_read(c: Client) {
    let id = seeded_exercise(&c).await;
    let (status, body) = c
        .put_bytes(
            &format!("/api/gym/exercises/{id}/image"),
            PNG.to_vec(),
            "image/png",
            Some(TOKEN),
        )
        .await;
    assert_eq!(status, StatusCode::OK, "{body}");
    let key = body["image_key"].as_str().unwrap().to_owned();
    assert!(
        key.starts_with(&format!("exercises/{id}/")) && key.ends_with(".png"),
        "{key}"
    );

    let resp = c
        .get_raw(&format!("/api/gym/images/{key}"), Some(TOKEN))
        .await;
    assert_eq!(resp.status(), StatusCode::OK);
    assert_eq!(resp.headers()["content-type"], "image/png");
    assert!(
        resp.headers()["cache-control"]
            .to_str()
            .unwrap()
            .contains("immutable")
    );
    assert_eq!(resp.bytes().await.unwrap().as_ref(), PNG);
}

async fn unknown_exercise_is_404(c: Client) {
    let (status, body) = c
        .put_bytes(
            &format!("/api/gym/exercises/{}/image", uuid()),
            PNG.to_vec(),
            "image/png",
            Some(TOKEN),
        )
        .await;
    assert_eq!(status, StatusCode::NOT_FOUND);
    assert_eq!(body["code"], "not_found");
}

async fn wrong_type_is_415(c: Client) {
    let id = seeded_exercise(&c).await;
    let (status, body) = c
        .put_bytes(
            &format!("/api/gym/exercises/{id}/image"),
            PNG.to_vec(),
            "image/gif",
            Some(TOKEN),
        )
        .await;
    assert_eq!(status, StatusCode::UNSUPPORTED_MEDIA_TYPE);
    assert_eq!(body["code"], "unsupported_media_type");
}

async fn too_large_is_413(c: Client) {
    let id = seeded_exercise(&c).await;
    let big = vec![0u8; 5 * 1024 * 1024 + 1];
    let (status, body) = c
        .put_bytes(
            &format!("/api/gym/exercises/{id}/image"),
            big,
            "image/jpeg",
            Some(TOKEN),
        )
        .await;
    assert_eq!(status, StatusCode::PAYLOAD_TOO_LARGE);
    assert_eq!(body["code"], "payload_too_large");
}

async fn missing_or_bad_key_is_404(c: Client) {
    let (status, _) = c
        .get("/api/gym/images/exercises/nope/1-00000001.jpg", Some(TOKEN))
        .await;
    assert_eq!(status, StatusCode::NOT_FOUND);
    let (status, _) = c
        .get("/api/gym/images/exercises/../wrangler.toml", Some(TOKEN))
        .await;
    assert_eq!(status, StatusCode::NOT_FOUND);
}

async fn requires_token(c: Client) {
    let (status, _) = c
        .get("/api/gym/images/exercises/x/1-00000001.jpg", None)
        .await;
    assert_eq!(status, StatusCode::UNAUTHORIZED);
}
